[project]
name = "fknc-calc"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "orjson>=3.11.7",
    "pydantic>=2.12.5",
    "pypinyin>=0.55.0",
    "streamlit>=1.54.0",
]

[tool.uv]
package = true
